name: hello_world

# trigger
on:
- push

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - id: s00
    # eunning shell(bash/zsh etc) commd 
      run: echo "current time in Github $(date), ${GITHUB_OUTPUT}"
    - id: s01
      run: echo "CUR_DATE=$(date)" >> $GITHUB_OUTPUT
    - id: s02
      #cat /new1/notes.txt
      uses: mscoutermarsh/cowsays-action@v1
      with:
        # step - context
        text: 'hi ${{ steps.s01.outputs.CUR_DATE }}'
        color: red
